
public class costs {
	 int AUTOMATED_FACTORY_CAPACITY;
	 int MANUAL_FACTORY_CAPACITY;
	 int OUTSOURCED_GOODS_CAPACITY;
	
	 int MATERIAL_BLOCK;
	 int CONVERSION_BLOCK;
	
	 int OCCUPANCY_ONLY;
	 int OUTSOURCED_OPERATION;
	 int MANUAL_FACTORY_PERIOD_ONE;
	 int MANUAL_FACTORY_PERIOD_TWO;
	 int AUTOMATED_FACTORY_PERIOD;
	
	 int OUTSOURCED_GOODS_REVENUE;
	 int MANUAL_FACTORY_REVENUE;
	 int AUTOMATED_FACTORY_REVENUE;
	 
	 costs(){}
}
