public class denim_costs extends costs{{
	 AUTOMATED_FACTORY_CAPACITY=650;
	 MANUAL_FACTORY_CAPACITY=150;
	 OUTSOURCED_GOODS_CAPACITY=204;
	
	 MATERIAL_BLOCK=144;
	 CONVERSION_BLOCK=144;
	
	 OCCUPANCY_ONLY=10;
	 OUTSOURCED_OPERATION=10;
	 MANUAL_FACTORY_PERIOD_ONE=25;
	 MANUAL_FACTORY_PERIOD_TWO=31;
	 AUTOMATED_FACTORY_PERIOD=120;
	
	 OUTSOURCED_GOODS_REVENUE=270;
	 MANUAL_FACTORY_REVENUE=540;
	 AUTOMATED_FACTORY_REVENUE=1090;
}
}
