
public class leather_costs extends costs {{
	 AUTOMATED_FACTORY_CAPACITY=1000;
	 MANUAL_FACTORY_CAPACITY=250;
	 OUTSOURCED_GOODS_CAPACITY=516;
	
	 MATERIAL_BLOCK=660;
	 CONVERSION_BLOCK=300;
	
	 OCCUPANCY_ONLY=10;
	 OUTSOURCED_OPERATION=10;
	 MANUAL_FACTORY_PERIOD_ONE=48;
	 MANUAL_FACTORY_PERIOD_TWO=62;
	 AUTOMATED_FACTORY_PERIOD=140;
	
	 OUTSOURCED_GOODS_REVENUE=660;
	 MANUAL_FACTORY_REVENUE=1320;
	 AUTOMATED_FACTORY_REVENUE=2640;
}
}
