
public class nylon_costs  extends costs{{
	 AUTOMATED_FACTORY_CAPACITY=450;
	 MANUAL_FACTORY_CAPACITY=75;
	 OUTSOURCED_GOODS_CAPACITY=108;
	
	 MATERIAL_BLOCK=84;
	 CONVERSION_BLOCK=108;
	
	 OCCUPANCY_ONLY=10;
	 OUTSOURCED_OPERATION=10;
	 MANUAL_FACTORY_PERIOD_ONE=23;
	 MANUAL_FACTORY_PERIOD_TWO=29;
	 AUTOMATED_FACTORY_PERIOD=50;
	
	 OUTSOURCED_GOODS_REVENUE=150;
	 MANUAL_FACTORY_REVENUE=300;
	 AUTOMATED_FACTORY_REVENUE=600;
}
}
